121 req add guidance for installing packages hosted on GitHub in new versions of rstudio desktop
Public-Health-Scotland/technical-docs pull request #122
Opened 2024-10-10 14:25 UTC by JFix89

# Pull Request Details

**Issue Number**: #121 

**Type**: Documentation

## Description of the Change

Add instructions on installing packages from GitHub for users of the newest version of RStudio Desktop.

### Verification Process

Tested personally and with one other user in the pilot group.

### Additional Work Required

NA

## Release Notes

Add instructions on installing packages from GitHub for users of the newest version of RStudio Desktop.

2024-10-10 14:26 UTC, JFix89 commented
Hi all, I've just drafted these instructions today after trying to troubleshoot the issues we've been having with the latest version of RStudio Desktop. DaS are going to make separate changes that will get around not being able to install from CRAN, although the issues with GitHub are still being investigated. In the meantime, these instructions should help users install packages from GitHub where necessary.

2024-10-14 09:50 UTC, Moohan requested changes
Unless the fix for CRAN has broken it... would it be worthwhile adding a note that PHS packages (phsmethods etc.) can be installed with `install.packages("phsmethods", repos = "https://ppm.publichealthscotland.org/all-r/latest")` this is a much simpler process (I think) and also means people should get a more properly versioned package (rather than just the latest commit).

It might also be good to add a final line noting that you can check the installed version of a package with `packageVersion("RDCOMClient")` which might be useful for comparing with colleagues (although when installing from GitHub you will likely end up with x.x.x.9000 where any small changes won't change the version number...

2024-10-14 09:50 UTC, Moohan commented on R/How to install packages hosted on GitHub with RStudio Desktop.md
> +# How to install packages hosted on GitHub in RStudio Desktop
Make clear that this is a 'workaround' and not expected to be permanent.

2024-10-14 09:50 UTC, Moohan commented on R/How to install packages hosted on GitHub with RStudio Desktop.md
> +```devtools::install("C:/Users/ldap_username/Downloads/folder_name/folder_name")```
`{remotes}` is a better option than `{devtools}` as it's much more lightweight (no dependencies) and doesn't require completion (no requirement for RTools).

```suggestion
```remotes::install_local("C:/Users/<USERNAME>/Downloads/<package>-main.zip")```
```

2024-10-14 09:50 UTC, Moohan commented on R/How to install packages hosted on GitHub with RStudio Desktop.md
> +Open RStudio Desktop and run the following code, replacing 'ldap_username' with your own LDAP username and 'folder_name' (2x) with the name of the unzipped folder in Downloads:
I'm not 100% sure if this applies to `{devtools}` (but I suspect it does), and if following my suggestion on using `{remotes}`, then there is no need to unzip the folder as  `install_local()` can take the zip file directly and deal with it from there.

```suggestion
#### 3. Install the package in RStudio Desktop
Open RStudio Desktop and run the following code, replacing `<USERNAME>` with your own LDAP username and `<package>` with the name of the zipped file in Downloads:
```

2024-10-14 09:50 UTC, Moohan commented on R/How to install packages hosted on GitHub with RStudio Desktop.md
> +The package will then be installed to the R library, and a message in the console will confirm this. The zipped and unzipped folders in 'Downloads' can then be deleted. To update or reinstall the pac
```suggestion
The package will then be installed in the R library, and a message in the console will confirm this. The files in 'Downloads' can then be deleted. To update or reinstall the package at any point in the future, these steps will need to be repeated.
```

2024-10-14 09:54 UTC, JFix89 commented
Thanks for reviewing @Moohan! Having a meeting this afternoon to discuss next steps with Desktop so will hold off making any changes until we know what's happening next. It might not be relevant if DaS have come up with a solution in the meantime.

2024-10-16 07:48 UTC, JFix89 commented
Closing for now as this guidance will hopefully be redundant once DaS package a newer version of RStudio Desktop with dedicated .Renviron and .Rprofile files.

2024-10-16 07:48 UTC, closed without merging